name: jobs example

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step do job1
        run: echo Hello, world! Job1.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do job2
        run: echo Hello, world! Job2
